### PR TITLE
~port authority meetings~ 🚌🚍🚏🚎🚃

### PR DESCRIPTION
**Pull request by vnbcs**
he*l yeah my dudes i got the port authority meetings 🚍🚍🚍🚍
close this boy -> #48

### CODE REVIEW

**Comment by vnbcs** [comment]
@ben-nathanson the flake8 tests are failing due to having lines that are too long. these lines are urls. i'm not sure what to do to fix this. i fixed isort probs and reformatted according to yapf.

**Comment by ben-nathanson** [comment]
@vnbcs Hi Eva. Sorry for taking so long to respond - I must have missed the notification. In any case one way to please the yapf gods is
`alle_port_authority.py`:
```Python
    start_urls = [(
        "https://www.portauthority.org"
        "/inside-Port-Authority/"
        "Port-Authority-Board/"
        "Board-Meeting-Information/"
    )]
```
`test_alle_port_authority.py`:
```Python
SOURCE = (
    "https://www.portauthority.org"
    "/inside-Port-Authority/"
    "Port-Authority-Board/"
    "Board-Meeting-Information/"
)

test_response = file_response(join(dirname(__file__), "files", "alle_port_authority.html"), SOURCE)
```
It also appears as though `alle_port_authority` is missing from the `tests/files` directory, meaning Pytest will fail. I can see you wrote some tests for it though. Maybe you forgot to add the file?

**Comment by bonfirefan** [comment]
Hey there - try syncing your updates to latest with 
```
git fetch upstream
git merge upstream/master
```
and delete the travis file if needed. You may have some pipfile and pipfile lock conflicts - try to keep the changes from upstream with `git checkout --theirs -- <filename>` on any merge conflicts.

**Comment by bonfirefan** [comment]
@vnbcs Eva you still working on this?

**Comment by ben-nathanson** [comment]
Closing for now. Happy to reopen if this branch becomes active again.

**Pull request closed without merging**
