### PR TITLE
Freeze pytest fix bug

### PR DESCRIPTION
**Pull request by bonfirefan**

### CODE REVIEW

**Comment by ben-nathanson** [comment]
Just for my own understanding, a few questions:
- What was the bug being fixed / How did freezing Pytest to v4.4.0 fix it?
- Should we drop Python 3.5 and add 3.8 at some point?

**Comment by bonfirefan** [comment]
This sadly did not fix the issue (seemed to be more about a rogue 3.8 installation, so I may just kill this branch). 
There was a bug that was popping up with #102 that due to an update of pytest that was requiring `atomcwrites`. This problem only popped up with new installations of the project and wasn't appearing with those of us with installations of pytest that were <5.0

**Comment by ben-nathanson** [comment]
We do not currently support Python 3.8.

**Comment by bonfirefan** [comment]
This is a problem with pytest versions > 5.0 : https://gitlab.alpinelinux.org/alpine/aports/issues/8975

**Pull request closed without merging**
